### ISSUE TITLE
Would this work on a vhost setup? If so, how?

### ISSUE THREAD

**Issue by MaximilianKohler** [samyogdhital/listmonk-caddy-reverse-proxy#1]
Would you just put this in your main nginx config?

```
server {
	    listen              443 ssl;
		server_name			listmonk.example.com; 

  location / {
     proxy_pass  http://127.0.0.1:9000;
     proxy_set_header   Host            $http_host;
     proxy_set_header   X-Real-IP       $remote_addr;
     proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;  
    }

}

server {
    listen              80;
	server_name			listmonk.example.com; 
	  location / {
return 301 https://$host$request_uri;
	  }
}
```
And then change:
```
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
```
To:
```
  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 82:80
      - 8443:443
```
Since they'll conflict with the existing ports?

EDIT: nvm, caddy isn't needed for vhost that's already running nginx. You can delete this; I don't have that option.
